# Generated by Django 5.0.6 on 2026-06-02 02:30

import ferremas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferremas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='numero_pedido',
            field=models.CharField(default=ferremas.models.generar_numero_pedido, max_length=20, unique=True),
        ),
    ]
