# Generated by Django 5.0.6 on 2026-05-28 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferremas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='metodo_pago',
            field=models.CharField(choices=[('WEBPAY', 'Transbank Webpay Plus'), ('TRANSFERENCIA', 'Transferencia Bancaria')], default='WEBPAY', max_length=20),
        ),
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de Pago'), ('ESPERANDO_TRANSFERENCIA', 'Esperando Confirmación Bancaria'), ('PAGADA', 'Pagada Exitosamente'), ('RECHAZADA', 'Pago Rechazado'), ('CANCELADA', 'Cancelada por el Usuario / Timeout')], default='PENDIENTE', max_length=30),
        ),
    ]
