# Generated by Django 5.0.6 on 2026-06-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferremas', '0003_producto_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='usd',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
