# Generated by Django 5.0.6 on 2024-06-28 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patitasYCompania', '0005_contactmessage_telefono'),
    ]

    operations = [
    ]
