# Generated by Django 5.0.6 on 2024-06-29 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patitasYCompania', '0009_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_purchased',
            field=models.BooleanField(default=False),
        ),
    ]
